version: '3'
services:
  web:
    image: gmail2cal
    build: .
    container_name: gmail2cal
    restart: always
    environment:
      - CREDENTIALS=${CREDENTIALS}
      - REFRESH_TOKEN_PATH=/app/tokens/token.json
    volumes:
      - ./tokens:/app/tokens
    ports:
      - "8446:3000"